/*
 * Tax_sheet.java
 *
 * Created on 21 Jan, 2013, 8:50:38 PM
 */

package income_tax_calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author Tapender Singh Yadav
 */
 
public class Tax_sheet extends javax.swing.JFrame {

    /** Creates new form Tax_sheet */
    public Tax_sheet() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        main_panel = new javax.swing.JPanel();
        table_heading = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_cal = new javax.swing.JTable();
        Reset = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Label_Year = new javax.swing.JLabel();
        Text_Field_year1 = new java.awt.TextField();
        to = new javax.swing.JLabel();
        Text_field_year2 = new java.awt.TextField();
        Text_field_emp_code = new java.awt.TextField();
        Emp_code = new javax.swing.JLabel();
        Label_name = new javax.swing.JLabel();
        Text_field_name = new java.awt.TextField();
        Label_Dept = new javax.swing.JLabel();
        Text_field_dept = new java.awt.TextField();
        tot_panel = new javax.swing.JPanel();
        total_label = new javax.swing.JLabel();
        Text_field_sal = new java.awt.TextField();
        nps_label = new javax.swing.JLabel();
        Text_field_nps = new java.awt.TextField();
        LTC_label = new javax.swing.JLabel();
        Text_field_ltc = new java.awt.TextField();
        tot_label = new javax.swing.JLabel();
        tot_text_field = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        hra_label_exemption = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        textField3 = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        textField4 = new java.awt.TextField();
        education_allowance = new javax.swing.JLabel();
        label_prof_tax = new javax.swing.JLabel();
        text_field_prof_tax = new java.awt.TextField();
        income_label = new java.awt.Label();
        text_field_sal = new java.awt.TextField();
        Annual_prop_val_label = new javax.swing.JLabel();
        text_field_prop_val = new java.awt.TextField();
        Interest_on_prop_label = new javax.swing.JLabel();
        text_field_interest_for_self = new java.awt.TextField();
        label_interest_frm_prop = new javax.swing.JLabel();
        text_field_loss = new java.awt.TextField();
        label_sources = new javax.swing.JLabel();
        text_field_jee = new java.awt.TextField();
        text_field_bonus = new java.awt.TextField();
        text_field_bank_in = new java.awt.TextField();
        text_field_prof_fee = new java.awt.TextField();
        text_field_pro_alo = new java.awt.TextField();
        text_field_any_inc = new java.awt.TextField();
        label_gross_tot_inc = new javax.swing.JLabel();
        text_field_gross_tot_inc = new java.awt.TextField();
        label_heading_deductions = new javax.swing.JLabel();
        label_ded1 = new javax.swing.JLabel();
        label_ded2 = new javax.swing.JLabel();
        label_ded3 = new javax.swing.JLabel();
        label_ded4 = new javax.swing.JLabel();
        text_field_ded1 = new java.awt.TextField();
        text_field_ded2 = new java.awt.TextField();
        text_field_ded3 = new java.awt.TextField();
        text_field_ded4 = new java.awt.TextField();
        label_ded5 = new javax.swing.JLabel();
        text_field_ded5 = new java.awt.TextField();
        label_ded6 = new javax.swing.JLabel();
        text_field_ded6 = new java.awt.TextField();
        label_ded7 = new javax.swing.JLabel();
        text_field_ded7 = new java.awt.TextField();
        label_ded8 = new javax.swing.JLabel();
        text_field_ded8 = new java.awt.TextField();
        label_ded9 = new javax.swing.JLabel();
        label_ded10 = new javax.swing.JLabel();
        label_ded11 = new javax.swing.JLabel();
        label_ded12 = new javax.swing.JLabel();
        text_field_ded9 = new java.awt.TextField();
        text_field_ded10 = new java.awt.TextField();
        text_field_ded11 = new java.awt.TextField();
        text_field_ded12 = new java.awt.TextField();
        label_jee = new javax.swing.JLabel();
        label_bonus = new javax.swing.JLabel();
        label_bank_in = new javax.swing.JLabel();
        label_any_inc = new javax.swing.JLabel();
        label_pro_allo = new javax.swing.JLabel();
        label_prof_fee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Income Tax Calculator");
        setBounds(new java.awt.Rectangle(0, 0, 1000, 600));

        table_heading.setFont(new java.awt.Font("Dialog", 1, 18));
        table_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        table_heading.setText("Fill the following table below :");

        Table_cal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"March,", null, null, null, null, null, null, "0.00", null},
                {"April,", null, null, null, null, null, null, "0.00", null},
                {"May,", null, null, null, null, null, null, "0.00", null},
                {"June,", null, null, null, null, null, null, "0.00", null},
                {"July,", null, null, null, null, null, null, "0.00", null},
                {"Aug,", null, null, null, null, null, null, "0.00", null},
                {"Sept,", null, null, null, null, null, null, "0.00", null},
                {"Oct,", null, null, null, null, null, null, "0.00", null},
                {"Nov,", null, null, null, null, null, null, "0.00", null},
                {"Dec,", null, null, null, null, null, null, "0.00", null},
                {"Jan,", null, null, null, null, null, null, "0.00", null},
                {"Feb,", null, null, null, null, null, null, "0.00", null},
                {"Total", "0", "0", "0", "0", "0", "0", "0.00", "0.00"}
            },
            new String [] {
                "Months", "Basic + GP", "DA", "TA", "HRA", "Arrear & Others", "Children Education Allowance", "Total Salary", "Employee Contri to NPS"
            }
        ));
        Table_cal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Table_calMouseEntered(evt);
            }
        });
        Table_cal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_calKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Table_cal);

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Income Tax - Sheet");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_Year.setFont(new java.awt.Font("Dialog", 0, 18));
        Label_Year.setText("Financial Year  :");

        Text_Field_year1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                Text_Field_year1TextValueChanged(evt);
            }
        });
        Text_Field_year1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Text_Field_year1KeyReleased(evt);
            }
        });

        to.setFont(new java.awt.Font("Dialog", 0, 18));
        to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        to.setText("to");

        Emp_code.setFont(new java.awt.Font("Dialog", 0, 18));
        Emp_code.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Emp_code.setText("Employee Code  :");

        Label_name.setFont(new java.awt.Font("Dialog", 0, 18));
        Label_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_name.setText("Name  :");

        Text_field_name.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                Text_field_nameTextValueChanged(evt);
            }
        });

        Label_Dept.setFont(new java.awt.Font("Dialog", 0, 18));
        Label_Dept.setText("Department  :");

        Text_field_dept.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                Text_field_deptTextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Label_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_field_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Text_field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emp_code))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Text_Field_year1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_field_year2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Text_field_emp_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(666, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Text_field_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Emp_code, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Text_field_emp_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_field_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Label_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Text_field_year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(to)
                            .addComponent(Text_Field_year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Name");

        total_label.setFont(new java.awt.Font("Century", 1, 14));
        total_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_label.setText(" Total Salary : ");

        Text_field_sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_field_salMouseClicked(evt);
            }
        });

        nps_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12));
        nps_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nps_label.setText("Employer's Contribution to NPS : ");

        Text_field_nps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_field_npsMouseClicked(evt);
            }
        });

        LTC_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12));
        LTC_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTC_label.setText("Leave Encashment UNDER  LTC : ");

        tot_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12));
        tot_label.setText("Total");

        tot_text_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tot_text_fieldMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exemptions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 1, 14), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        hra_label_exemption.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12));
        hra_label_exemption.setText("Qualifying exemption on HRA (u/s 10) :");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12));
        jLabel2.setText("Transport Allowance (u/s2BB10) Rs 800pm :");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12));
        jLabel3.setText("Children Education Allowance (u/s2BB5) Rs 1200 pa :");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jLabel4.setText("Gross Salary");

        textField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textField4MouseClicked(evt);
            }
        });

        education_allowance.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        education_allowance.setForeground(new java.awt.Color(255, 0, 0));
        education_allowance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        education_allowance.setText("Deduction u/s 16 (iii)   Education Allowances");

        label_prof_tax.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_prof_tax.setText("Professional  Tax :");

        income_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        income_label.setText("Income from Salary");

        text_field_sal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_salMouseClicked(evt);
            }
        });

        Annual_prop_val_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Annual_prop_val_label.setText("Annual Value of self occupied/residential property :");

        Interest_on_prop_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        Interest_on_prop_label.setText("Interest on loan taken for construction of self :");

        label_interest_frm_prop.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_interest_frm_prop.setText("Income/(loss) from House Property :");

        text_field_loss.setName(""); // NOI18N
        text_field_loss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_lossMouseClicked(evt);
            }
        });

        label_sources.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_sources.setForeground(new java.awt.Color(255, 0, 0));
        label_sources.setText("Income from other sources (JEE,Bonus,Bank Interest )");

        text_field_jee.setText("0.0");

        text_field_bonus.setText("0.0");

        text_field_bank_in.setText("0.0");

        text_field_prof_fee.setText("0.0");

        text_field_pro_alo.setText("0.0");

        text_field_any_inc.setText("0.0");

        label_gross_tot_inc.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_gross_tot_inc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_gross_tot_inc.setText("Gross Total Income");

        text_field_gross_tot_inc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_gross_tot_incMouseClicked(evt);
            }
        });

        label_heading_deductions.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_heading_deductions.setForeground(new java.awt.Color(255, 0, 0));
        label_heading_deductions.setText("Deductions :");

        label_ded1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded1.setText("U/s (80D,80DD,80DDB,80E,80G,80QQB,80RRB,80U)");

        label_ded2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded2.setText("u/s 80C,80CCC & 80CCD(1)  (limited to Rs 100000/-)");

        label_ded3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded3.setText("u/s 80CCG (Investment under Equity Saving Scheme Limited to Rs 25000/-)");

        label_ded4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded4.setText("U/s 80CCD(2) (Employer's cont. to NPS subject to maximum 10% of salary)");

        text_field_ded2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_field_ded2KeyReleased(evt);
            }
        });

        label_ded5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_ded5.setText("Taxable income  (rounded off Rs. 10)");

        text_field_ded5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_ded5MouseClicked(evt);
            }
        });

        label_ded6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_ded6.setText("Tax on total income");

        text_field_ded6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_ded6MouseClicked(evt);
            }
        });

        label_ded7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded7.setText("Education cess 3% on income tax ");

        text_field_ded7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_ded7MouseClicked(evt);
            }
        });

        label_ded8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_ded8.setText("Total tax including education cess ");

        text_field_ded8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_ded8MouseClicked(evt);
            }
        });

        label_ded9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded9.setText("Tax deducted from salary u/s 192");

        label_ded10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded10.setText("Tax deducted on bank interest u/s 193");

        label_ded11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_ded11.setText("Tax deducted on consultancy, professional charges etc. u/s 194J");

        label_ded12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        label_ded12.setText("Balance Tax payable from salary  (rounded off Rs. 10) ");

        text_field_ded12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_field_ded12MouseClicked(evt);
            }
        });

        label_jee.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_jee.setText("JEE");

        label_bonus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_bonus.setText("Bonus");

        label_bank_in.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_bank_in.setText("Bank Interest");

        label_any_inc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_any_inc.setText("Any other income");

        label_pro_allo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_pro_allo.setText("Professional Allowance");

        label_prof_fee.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        label_prof_fee.setText("Professional fee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_heading_deductions, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_gross_tot_inc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(education_allowance)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_sources, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                            .addComponent(label_interest_frm_prop, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
                        .addGap(387, 387, 387))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ded2)
                        .addContainerGap(694, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ded3)
                        .addContainerGap(559, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ded4)
                        .addContainerGap(563, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ded1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(label_ded5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ded6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label_ded8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_ded7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                                            .addComponent(hra_label_exemption, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(income_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label_prof_tax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Interest_on_prop_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Annual_prop_val_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_field_sal, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                            .addComponent(text_field_prof_tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(text_field_prop_val, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                            .addComponent(text_field_interest_for_self, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                            .addComponent(text_field_loss, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_ded12)
                                    .addComponent(label_ded11)
                                    .addComponent(label_ded10)
                                    .addComponent(label_ded9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label_prof_fee)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(text_field_prof_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(label_pro_allo))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label_jee)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(text_field_jee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72)
                                                .addComponent(label_bonus)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(text_field_bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                                .addComponent(label_bank_in))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(text_field_pro_alo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                                .addComponent(label_any_inc)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(text_field_ded1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_gross_tot_inc, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                        .addComponent(text_field_ded2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_field_ded9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_field_any_inc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_field_bank_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hra_label_exemption, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(education_allowance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_field_prof_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_prof_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(income_label, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(text_field_sal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Annual_prop_val_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_field_prop_val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Interest_on_prop_label)
                    .addComponent(text_field_interest_for_self, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_interest_frm_prop)
                    .addComponent(text_field_loss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_sources)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_field_jee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_field_bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_bonus)
                            .addComponent(label_jee)
                            .addComponent(label_bank_in)))
                    .addComponent(text_field_bank_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_field_prof_fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_prof_fee))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(text_field_any_inc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(text_field_gross_tot_inc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(label_gross_tot_inc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(label_pro_allo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label_any_inc)
                        .addComponent(text_field_pro_alo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_heading_deductions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_ded1))
                    .addComponent(text_field_ded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_ded2)
                    .addComponent(text_field_ded2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ded3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_ded4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(text_field_ded3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_field_ded4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ded5)
                    .addComponent(text_field_ded5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ded6)
                    .addComponent(text_field_ded6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ded7)
                    .addComponent(text_field_ded7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ded8)
                    .addComponent(text_field_ded8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_ded9)
                        .addGap(18, 18, 18)
                        .addComponent(label_ded10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(text_field_ded9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_field_ded10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_field_ded11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ded11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_field_ded12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ded12))
                .addContainerGap())
        );

        javax.swing.GroupLayout tot_panelLayout = new javax.swing.GroupLayout(tot_panel);
        tot_panel.setLayout(tot_panelLayout);
        tot_panelLayout.setHorizontalGroup(
            tot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tot_panelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tot_panelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(tot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tot_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LTC_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total_label, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nps_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addGroup(tot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Text_field_sal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text_field_nps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text_field_ltc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tot_text_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        tot_panelLayout.setVerticalGroup(
            tot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tot_panelLayout.createSequentialGroup()
                .addGroup(tot_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tot_panelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(total_label, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nps_label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LTC_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tot_label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tot_panelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Text_field_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Text_field_nps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(Text_field_ltc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(tot_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(table_heading))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tot_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(table_heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tot_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(main_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2079, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        


private void Table_calKeyReleased(java.awt.event.KeyEvent evt) {                                      
        double basic;
        double hra;
        double arrear;
        double edu_all;
        double da;
        double ta;
        double total;
        double nps;
        int j=1;
        double sum,sum1=0.0,sum2=0.0,sum3=0.0,sum4=0.0,sum5=0.0,sum6=0.0,sum7;
        sum7 = 0.0;
        sum = 0.00;
        for(int i=0;i<=11;i++)
        {
                total = 0.0;
                String str = (String) Table_cal.getValueAt(i, j);
                basic = Float.parseFloat(str);
                sum = sum + basic;
                Table_cal.setValueAt(sum,12,j);
                da = (basic*15)/100;
                sum1 = sum1 + da;
                Table_cal.setValueAt(sum1,12,j+1);
                ta = (basic*10)/100;
                sum2 = sum2 + ta;
                Table_cal.setValueAt(sum2,12,j+2);
                Table_cal.setValueAt(da, i, j+1);
                Table_cal.setValueAt(ta, i, j+2);
                
                total = total + (basic+da+ta);
                Table_cal.setValueAt(total,i,j+6);
                str = (String) Table_cal.getValueAt(i,j+3);
                if(basic>=0 && basic<=25000)
                {
                    if ((basic * 10) / 100 >= Float.parseFloat(str))
                    {
                        hra = Float.parseFloat(str);
                        total = total + hra;
                        Table_cal.setValueAt(total, i, j+6);
                        sum3 = sum3 + hra;
                        Table_cal.setValueAt(sum3,12,j+3);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Enter the value of HRA less than 10% of the Basic+GP as per Govt. of India Act.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                        Table_cal.setValueAt(null, i, j+3);
                    }
                }
                else if(basic>25000 && basic<=50000)
                {
                    if((basic * 20)/100 >= Float.parseFloat(str))
                    {
                        hra = Float.parseFloat(str);
                        total = total + hra;
                        Table_cal.setValueAt(total, i, j+6);
                        sum3 = sum3 + hra;
                        Table_cal.setValueAt(sum3,12,j+3);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Enter the value of HRA less than 20% of the Basic+GP as per Govt. of India Act.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                        Table_cal.setValueAt(null, i, j+3);
                    }
                }
                else
                {
                    if((basic * 30)/100 >= Float.parseFloat(str))
                    {
                        hra = Float.parseFloat(str);
                        total = total + hra;
                        Table_cal.setValueAt(total, i, j+6);
                        sum3 = sum3 + hra;
                        Table_cal.setValueAt(sum3,12,j+3);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Enter the value of HRA less than 30% of the Basic+GP as per Govt. of India Act.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                        Table_cal.setValueAt(null, i, j+3);
                    }

                }
                str = (String) Table_cal.getValueAt(i,j+4);
                arrear = Float.parseFloat(str);
                total = total + arrear;
                Table_cal.setValueAt(total,i,j+6);
                sum4 =sum4 + arrear;
                Table_cal.setValueAt(sum4,12,j+4);
                str = (String) Table_cal.getValueAt(i,j+5);
                edu_all = Float.parseFloat(str);
                total = total + edu_all;
                Table_cal.setValueAt(total, i, j+6);
                sum5 =sum5 + edu_all;
                Table_cal.setValueAt(sum5, 12, j+5);
                sum6 = sum6 + total;
                Table_cal.setValueAt(sum6,12,j+6);
                str = (String) Table_cal.getValueAt(i,j+7);
                if(total>=Float.parseFloat(str))
                {
                    nps = Float.parseFloat(str);
                    sum7 = sum7 + nps;
                    Table_cal.setValueAt(sum7,12,j+7);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Enter the value of NPS contribution less than Basic+GP", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                    Table_cal.setValueAt(null, i, j+7);
                }
        }
        for(int l=1;l<8;l++)
        {
            for(int k=0;k<12;k++)
            {
                String str = (String) Table_cal.getValueAt(k,l);
                sum = sum + Float.parseFloat(str);
                Table_cal.setValueAt(sum,12,l);
            }
        }
}                                     

    private void Table_calMouseEntered(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        Table_cal.setToolTipText("Fill the Table Row-wise starting from top left");
    }                                      

    private void Text_field_nameTextValueChanged(java.awt.event.TextEvent evt) {                                                 
        // TODO add your handling code here:
        String str = Text_field_name.getText();
        int len = str.length();
        for(int x=0;x<len;x++)
        {
            char c = str.charAt(x);
            if(c=='0'|| c=='1'|| c=='2'||c=='3'||c=='4'||c=='5'||c=='6'||c=='7'||c=='8'||c=='9')
            {
                JOptionPane.showMessageDialog(rootPane, "Enter a Valid Name", "Invalid Input",JOptionPane.ERROR_MESSAGE);
                Text_field_name.setText(null);
            }
                
        }
    }                                                

    private void Text_field_deptTextValueChanged(java.awt.event.TextEvent evt) {                                                 
        // TODO add your handling code here:
        String str = Text_field_dept.getText();
        int len = str.length();
        for(int x=0;x<len;x++)
        {
            char c = str.charAt(x);
            if(c=='0'|| c=='1'|| c=='2'||c=='3'||c=='4'||c=='5'||c=='6'||c=='7'||c=='8'||c=='9')
            {
                JOptionPane.showMessageDialog(rootPane, "Enter a valid entry in the Department", "Invalid Input",JOptionPane.ERROR_MESSAGE);
                Text_field_dept.setText(null);
            }
                
        }
    }                                                

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        if(evt.getSource()== Reset)
        {
            Text_field_name.setText(null);
            Text_field_emp_code.setText(null);
            Text_field_dept.setText(null);
            Text_Field_year1.setText(null);
            Text_field_year2.setText(null);
            for(int y=0;y<13;y++)
            {
                for(int z=1;z<9;z++)
                {
                    Table_cal.setValueAt(null, y, z);
                }
            }
            String arr1[] = {"March,","April,","May,","Jun,","July,","Aug,","Sept,","Oct,","Nov,","Dec,","Jan,","Feb,"};
            for(int col=0;col<12;col++)
            {
                Table_cal.setValueAt(arr1[col],col,0);
            }
            
        }
    }                                     

    private void Text_Field_year1KeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
        int year1 = Integer.parseInt(Text_Field_year1.getText());
        int year2 = year1+1;
        String str = Integer.toString(year2);
        Text_field_year2.setText(str);
        String str2 = Integer.toString(year1);
        String arr[] = new String[12];
        
        for(int row=0;row<12;row++)
        {
            arr[row]=(String) Table_cal.getValueAt(row, 0);
        }
        
        for(int enter=0;enter<12;enter++)
        {
            if(Text_Field_year1.getText().length() == 4 && enter<10)
            {
                Table_cal.setValueAt(arr[enter]+str2, enter, 0);
            }
            if(Text_field_year2.getText().length() == 4 && enter>=10)
            {
                Table_cal.setValueAt(arr[enter]+str, enter, 0);
            }
        }
    }                                            

    private void Text_Field_year1TextValueChanged(java.awt.event.TextEvent evt) {                                                  
        // TODO add your handling code here:
        String str = Text_Field_year1.getText();
        int len = str.length();
        if(len<=4)
        {
        for(int w=0;w<len;w++)
        {
            if(str.charAt(w)<'0' || str.charAt(w)>'9')
            {
                JOptionPane.showMessageDialog(rootPane,"Enter the Valid Year","Invalid Input",JOptionPane.ERROR_MESSAGE);
                Text_Field_year1.setText(null);
                Text_field_year2.setText(null);
            }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Enter the year less than 9999","Invalid Input",JOptionPane.ERROR_MESSAGE);
            Text_Field_year1.setText(null);
            Text_field_year2.setText(null);
        }
    }                                                 

    private void Text_field_salMouseClicked(java.awt.event.MouseEvent evt) {                                            
        try{
            String str = Double.toString((Double) Table_cal.getValueAt(12,7));
            Text_field_sal.setText(str);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(main_panel,e);
        }
    }                                           

    private void Text_field_npsMouseClicked(java.awt.event.MouseEvent evt) {                                            
        try{
            String str = Double.toString((Double) Table_cal.getValueAt(12,8));
            Text_field_nps.setText(str);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(main_panel,e);
        }
    }                                           

    private void tot_text_fieldMouseClicked(java.awt.event.MouseEvent evt) {                                            
        try{
            String str = (String) Text_field_ltc.getText();
            double ltc = Double.parseDouble(str);
            str = Double.toString((Double) Table_cal.getValueAt(12,8));
            double nps = Double.parseDouble(str);
            str = Double.toString((Double) Table_cal.getValueAt(12,7));
            double tot = Double.parseDouble(str);
            double sum = ltc+nps+tot;
            str=Double.toString(sum);
            tot_text_field.setText(str);
        }catch(Exception e){
            JOptionPane.showMessageDialog(main_panel,e);
        }
    }                                           

    private void textField4MouseClicked(java.awt.event.MouseEvent evt) {                                        
        double x;
        double y;
        double z;
        double gross_sum;
        String str = textField1.getText();
        x = Double.parseDouble(str);
        str = textField2.getText();
        y = Double.parseDouble(str);
        str = textField3.getText();
        z = Double.parseDouble(str);
        str = tot_text_field.getText();
        gross_sum = (Double.parseDouble(str))-(x+y+z);
        textField4.setText(Double.toString(gross_sum));
    }                                       

    private void text_field_salMouseClicked(java.awt.event.MouseEvent evt) {                                            
        double x;
        double inc_sal;
        String str = text_field_prof_tax.getText();
        x = Double.parseDouble(str);
        str = textField4.getText();
        inc_sal = (Double.parseDouble(str))-x;
        text_field_sal.setText(Double.toString(inc_sal));

    }                                           

    private void text_field_lossMouseClicked(java.awt.event.MouseEvent evt) {                                             
        double inc_hp;
        inc_hp = Double.parseDouble(text_field_prop_val.getText())-Double.parseDouble(text_field_interest_for_self.getText());
        text_field_loss.setText(Double.toString(inc_hp));
    }                                            

    private void text_field_gross_tot_incMouseClicked(java.awt.event.MouseEvent evt) {                                                      
        double a=0.0;
        double b=0.0;
        double c=0.0;
        double d=0.0;
        double e=0.0;
        double f=0.0;
        double x;
        double y;
        double z;
        a=Double.parseDouble(text_field_jee.getText());
        b=Double.parseDouble(text_field_bonus.getText());
        c=Double.parseDouble(text_field_bank_in.getText());
        d=Double.parseDouble(text_field_prof_fee.getText());
        e=Double.parseDouble(text_field_pro_alo.getText());
        f=Double.parseDouble(text_field_any_inc.getText());
        x=Double.parseDouble(text_field_sal.getText());
        y=Double.parseDouble(text_field_loss.getText());
        z=a+b+c+d+e+f+x+y;
        text_field_gross_tot_inc.setText(Double.toString(z));
    }                                                     

    private void text_field_ded5MouseClicked(java.awt.event.MouseEvent evt) {                                             
        double x = Double.parseDouble(text_field_ded1.getText());
        double y = 0.0;
        double z = Double.parseDouble(text_field_ded3.getText());
        double a = Double.parseDouble(text_field_ded4.getText());
        if((Double.parseDouble(text_field_ded2.getText()))<100000)
        {
            y=Double.parseDouble(text_field_ded2.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(main_panel,"Enter value less than 100000","Invalid Input", JOptionPane.ERROR_MESSAGE);
            text_field_ded2.setText(null);
        }
        double sum = Double.parseDouble(text_field_gross_tot_inc.getText());
        text_field_ded5.setText(Double.toString(sum-(x+y+z+a)));
    }                                            

    private void text_field_ded8MouseClicked(java.awt.event.MouseEvent evt) {                                             
        double x = Double.parseDouble(text_field_ded6.getText());
        //double y = x*0.03;
        //text_field_ded7.setText(Double.toString(y));
        double y = Double.parseDouble(text_field_ded7.getText());
        text_field_ded8.setText(Double.toString(x+y));

    }                                            

    private void text_field_ded2KeyReleased(java.awt.event.KeyEvent evt) {                                            
        double y=0.0;
        if((Double.parseDouble(text_field_ded2.getText()))<=100000)
        {
            y=Double.parseDouble(text_field_ded2.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(main_panel,"Enter value less than 100000","Invalid Input", JOptionPane.ERROR_MESSAGE);
            text_field_ded2.setText(null);
        }
    }                                           

    private void text_field_ded12MouseClicked(java.awt.event.MouseEvent evt) {                                              
        double a = Double.parseDouble(text_field_ded9.getText());
        double b = Double.parseDouble(text_field_ded10.getText());
        double c = Double.parseDouble(text_field_ded11.getText());
        double d = (Double.parseDouble(text_field_ded8.getText()))-(a+b+c);
        text_field_ded12.setText(Double.toString(d));
    }                                             

    private void text_field_ded6MouseClicked(java.awt.event.MouseEvent evt) {                                             
        if(Double.parseDouble(text_field_ded5.getText())<=200000)
        {
            text_field_ded6.setText("0.0");
        }
    else if(Double.parseDouble(text_field_ded5.getText())>200000 && Double.parseDouble(text_field_ded5.getText())<=500000)
    {
        double x = Double.parseDouble(text_field_ded5.getText());
        double y = x*0.10;
        text_field_ded6.setText(Double.toString(y));
    }
    else if(Double.parseDouble(text_field_ded5.getText())>500000 && Double.parseDouble(text_field_ded5.getText())<=1000000)
    {
        double x = Double.parseDouble(text_field_ded5.getText());
        double y = x*0.20+30000;
        text_field_ded6.setText(Double.toString(y));
    }
    else
    {
        double x = Double.parseDouble(text_field_ded5.getText());
        double y = x*0.30+130000;
        text_field_ded6.setText(Double.toString(y));
    }
    }                                            

    private void text_field_ded7MouseClicked(java.awt.event.MouseEvent evt) {                                             

    }                                            

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tax_sheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Annual_prop_val_label;
    private javax.swing.JLabel Emp_code;
    private javax.swing.JLabel Interest_on_prop_label;
    private javax.swing.JLabel LTC_label;
    private javax.swing.JLabel Label_Dept;
    private javax.swing.JLabel Label_Year;
    private javax.swing.JLabel Label_name;
    private javax.swing.JButton Reset;
    private javax.swing.JTable Table_cal;
    private java.awt.TextField Text_Field_year1;
    private java.awt.TextField Text_field_dept;
    private java.awt.TextField Text_field_emp_code;
    private java.awt.TextField Text_field_ltc;
    private java.awt.TextField Text_field_name;
    private java.awt.TextField Text_field_nps;
    private java.awt.TextField Text_field_sal;
    private java.awt.TextField Text_field_year2;
    private javax.swing.JLabel education_allowance;
    private javax.swing.JLabel hra_label_exemption;
    private java.awt.Label income_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_any_inc;
    private javax.swing.JLabel label_bank_in;
    private javax.swing.JLabel label_bonus;
    private javax.swing.JLabel label_ded1;
    private javax.swing.JLabel label_ded10;
    private javax.swing.JLabel label_ded11;
    private javax.swing.JLabel label_ded12;
    private javax.swing.JLabel label_ded2;
    private javax.swing.JLabel label_ded3;
    private javax.swing.JLabel label_ded4;
    private javax.swing.JLabel label_ded5;
    private javax.swing.JLabel label_ded6;
    private javax.swing.JLabel label_ded7;
    private javax.swing.JLabel label_ded8;
    private javax.swing.JLabel label_ded9;
    private javax.swing.JLabel label_gross_tot_inc;
    private javax.swing.JLabel label_heading_deductions;
    private javax.swing.JLabel label_interest_frm_prop;
    private javax.swing.JLabel label_jee;
    private javax.swing.JLabel label_pro_allo;
    private javax.swing.JLabel label_prof_fee;
    private javax.swing.JLabel label_prof_tax;
    private javax.swing.JLabel label_sources;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel nps_label;
    private javax.swing.JLabel table_heading;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField text_field_any_inc;
    private java.awt.TextField text_field_bank_in;
    private java.awt.TextField text_field_bonus;
    private java.awt.TextField text_field_ded1;
    private java.awt.TextField text_field_ded10;
    private java.awt.TextField text_field_ded11;
    private java.awt.TextField text_field_ded12;
    private java.awt.TextField text_field_ded2;
    private java.awt.TextField text_field_ded3;
    private java.awt.TextField text_field_ded4;
    private java.awt.TextField text_field_ded5;
    private java.awt.TextField text_field_ded6;
    private java.awt.TextField text_field_ded7;
    private java.awt.TextField text_field_ded8;
    private java.awt.TextField text_field_ded9;
    private java.awt.TextField text_field_gross_tot_inc;
    private java.awt.TextField text_field_interest_for_self;
    private java.awt.TextField text_field_jee;
    private java.awt.TextField text_field_loss;
    private java.awt.TextField text_field_pro_alo;
    private java.awt.TextField text_field_prof_fee;
    private java.awt.TextField text_field_prof_tax;
    private java.awt.TextField text_field_prop_val;
    private java.awt.TextField text_field_sal;
    private javax.swing.JLabel to;
    private javax.swing.JLabel tot_label;
    private javax.swing.JPanel tot_panel;
    private java.awt.TextField tot_text_field;
    private javax.swing.JLabel total_label;
    // End of variables declaration                   
}
